### PR TITLE
Simple Web App

### PR DESCRIPTION
**Pull request by bbiehl**
Non funziona.

### CODE REVIEW

**Comment by sumeetjain** [comment]
What are you trying (e.g. what command are you executing)? What are you expecting to happen? What is actually happening?

**Comment by bbiehl** [comment]
By all accounts these links should be working. 

a href="/about">About Us
a href="/favorites">Our Favorite Things

So for some reason the server does not know these pages exist.

**Comment by sumeetjain** [comment]
You need to define controller actions that deal with those request paths.

For example, your controller action for the About response has the following line:

`MyApp.get "/" do`

It is responding to a request to the root path, but it should be responding to a request to `"/about"`.

**Comment by bbiehl** [comment]
I thought I did define controller actions, for example this...

MyApp.get "/" do
  erb :"main/favorites"
end

But <code>http://localhost:9292/favorites</code> does not exist.  I'll go back and review the material.

**Comment by bbiehl** [comment]
Not very cool, but all tests pass.

**Comment by sumeetjain** [comment]
:+1:

**Pull request closed without merging**
