### PR TITLE
Amy's Web App Project

### PR DESCRIPTION
**Pull request by amymariewall**
Just opening this PR for possible future questions.

### CODE REVIEW

**Comment by sumeetjain** [comment]
What happens if you remove this controller action:

``` ruby
MyApp.get "/greet/Sumeet" do
  erb :"greet/Sumeet"
end
```

Do your tests continue to pass? How about going to http://localhost:9292/greet/Sumeet in your browser manually? If things still work, why?

tias, please.

**Comment by amymariewall** [comment]
I removed that controller action and the tests still passed, as did navigating to http://localhost:9292/greet/Sumeet. I think it still worked because the other controller action works instead and embeds Sumeet onto the page. I confirmed that by changing the Sumeet.erb file in the view folder so I would know which file was appearing when I made the request to go to /greet/Sumeet - it is indeed the autofill.erb file that is appearing. Now I am curious which one it will choose if  _both_ controller actions are there...TIAS-ing now.

**Comment by sumeetjain** [comment]
:+1:

**Comment by amymariewall** [comment]
Update: I have discovered that the order in which the controller actions appear in the file is what determines which to do if both apply.

**Comment by sumeetjain** [comment]
:+1:

**Pull request closed without merging**
